import Head from 'next/head'
import Image from 'next/image'
import Header from './../components/Header';
import Sidebar from './../components/Sidebar';
import Feed from './../components/Feed';
import Widgets from './../components/Widgets';
import { db } from "../firebase";
import { posts } from '../dummyPosts';

export default function Home( {posts} ) {
  return (
    <div className="h-screen bg-gray-100 overflow-hidden" >
      <Head>
        <title>Facebook by sammed.sankonatti</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex" >
          {/* <div className="hidden sm:inline-flex">
            <Sidebar  />
          </div> */}
          <Sidebar  />
          <Feed posts={posts} />
          <Widgets />
        </main>
    </div>
  )
}

export async function getServerSideProps(context){
   
  // const posts = await db.collection("posts").orderBy("timestamp", "desc").get();
  // const docs = posts.docs.map((post) => ({
  //   id: post.id,
  //   ...post.data(),
  //   timestamp: null,
  // }));

  return {
    props :{ posts: posts},
  };
}
